name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
      
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
   
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_TKN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mirjalal/android-30:lastest
